package wasmcloud:numbergen@0.1.0

interface generator {
    generate-guid: func() -> string
    random-in-range: func(min: u32, max: u32) -> u32
    random32: func() -> u32
}

default world numbergen {
    import generator
}