# codegen.toml

[[models]]
path = "lattice-control-interface.smithy"

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces/core"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]

##
## Rust language output
##
[rust]

# top-level output directory for rust files.
output_dir = "rust"

[rust.parameters]

[[rust.files]]
path = "src/control.rs"
namespace = "org.wasmcloud.lattice.control"

[tinygo]
output_dir = "tinygo"
formatter = ["goimports", "-w"]

[[tinygo.files]]
path = "control.go"
package = "latticecontrol"
namespace = "org.wasmcloud.lattice.control"

